# Options that directly affect gameplay
gameplay:
  # Options that affect the players
  player:
    # Maximum health for players in half-hearts (20 = 10 hearts, 15 = 7.5 hearts)
    # Cannot be less than 1
    max_health: 20
    # URL to a texture pack to ask players to download
    # Empty disables this
    texture_pack_url: ""
    # How fast a player walks (default .2) - speed cannot be < -1 or > 1
    walk_speed: .2
    # How fast a player flies (default .1) - speed cannot be < -1 or > 1
    fly_speed: .1
    # How long a player can hold their breath in ticks (1 tick = 1/20 second)
    # Default = 300 (15 seconds)
    maximum_underwater_air: 300
    # Can the player pick up items?
    # Default = true
    can_pick_up_items: true
  # Options relating to harder torches
  harder_torches:
    # Enable harder torches? Torches will require one flint, two coal, and one stick.
    enabled: false
  # Options relating to thirst (cannot be disabled)
  thirst:
    # Options relating to saturation drain
    saturation:
      # Saturation is out of this number. When the player's saturation is at 0, then the actual thirst begins to drain.
      # Saturation is calculated using the same method and drain amounts as drain is below. If a player drinks water,
      # their saturation goes to max, so this should be a low number.
      max: 250
    # Options relating to thirst drain
    drain:
      # Thirst is out of this number. The drain amounts are subtracted from this number, and then a percentage is made
      # by dividing the amount of thirst leftover by the max.
      max: 100000
      # Amount of thirst to drain if walking
      walk: 2
      # Amount of thirst to drain if sprinting
      sprint: 3
      # Amount of thirst to drain if sneaking
      sneak: 1
      # Amount of thirst to drain in addition to other amounts if jumping
      jump: 1
      # Amount of thirst to drain if on fire
      fire: 10
    # Options relating to thirst restore
    restore:
      # How much thirst (in % of XP bar) to restore after drinking a water bottle
      amount: 20
  # Options that affect the way zombies work
  zombies:
    # Ocean zombies spawn where squid should spawn. This makes it harder for survivors in the ocean to live.
    enable_ocean_zombies: false
    # Toxic spray will deal half damage to all zombies in a set radius around a player that uses it for a duration set
    # here. Toxic spray is, by default, one lapis dye + a torch in any pattern.
    toxicspray:
      # Enable the toxic spray?
      enabled: true
      # Radius to damage zombies in
      radius: 10.0
      # Interval in ticks (1 tick = 1/20 second) to check for zombies in spray radius
      interval: 10
      # Duration in seconds for one spray to last
      duration: 300
    # Options regarding baby zombie spawns
    babies:
      # Spawn baby zombies?
      enabled: true
      # Should babies always be given a speed boost?
      always_fast: true
      # 1/chance_out_of = percent chance of spawning a baby zombie
      chance_out_of: 50
    # Options regarding zombie speed
    speed:
      # Enable a speed boost for every zombie?
      enabled: false
      # What level should the speed boost be at?
      level: 2
    # Options regarding potion effects on zombies
    potions:
      # Use potion effects on zombies? Some are positive effects, and others are negative.
      enabled: true
      # 1/chance_out_of = percent chance of adding potion effects to a zombie
      chance_out_of: 5
      # Levels are 1 - 7
      minimum_level: 4
    # Options regarding hordes of zombies (many spawned at once)
    hordes:
      # 1/chance_out_of = percent chance of horde spawn
      # Minimum 2, maximum is Java's integer cap
      chance_out_of: 100
      # Least amount of zombies in any horde
      low: 10
      # Highest amount of zombies in any horde
      high: 40
  # Options regarding use of the radio
  radio:
    # What item to use for the radio. Compass is recommended, as it will combine the GPS & Radio function.
    item: COMPASS
    # Options regarding the radio's battery
    battery:
      # Use a battery on the radio? If the battery hits 0, the radio dies (same as having radio off).
      use: false
      # What item should recharge the battery in a crafting bench?
      item: GLOWSTONE_DUST
      # Options regarding how fast the battery drains
      drain:
        # Percent to drain
        amount: 5
        # Drain amount every interval minutes
        interval: 10
    # Radius for chat to go if radio is off
    local_chat_radius: 15
  # Options pertaining to phosphorous grenades
  grenades:
    # Enable phosphorous grenades?
    enabled: true
    # How much damage the grenade should deal on explosion (high percentile) 1/high_damage of max health
    high_damage: 3
    # How much damage the grenade should deal on explosion (low percentile) 1/low_damage of max health
    low_damage: 8
    # How long an entity will burn in seconds (low)
    low_burn_time: 8
    # How long an entity will burn in seconds (high)
    high_burn_time: 15
  # How often in seconds for the GPS to update its location. This affects player positions and compass resets.
  gps_update_interval: 5
  # World to enable RoyalSurvivors in
  world_to_use: zombies
  # Maximum mobs allowed to spawn (< 0 is disable)
  max_mobs_allowed: 1536
  # Spawn if the max amount of mobs is reached? This will remove the first zombie it finds to make room for the new one
  # if it is set to true. If it is false, no more zombies will spawn until one naturally despawns or is killed.
  spawn_if_maxed: false
  # Options regarding player deaths
  death:
    # Options regarding bans on player deaths
    ban:
      # Enable ban on player death
      enabled: true
      # Lenght of the ban in minutes. < 0 is permanent
      length: 180
      # Message to show the banned player. (supports color codes)
      message: "You died."
    # Put the player's drops into a chest where they were? (will have chests all over the place)
    drops_to_chest: true
    # Spawn a zombie where the player died?
    spawn_zombie: true

loot_chests:
  refill:
    # Should chests refill even if they aren't empty?
    if_not_empty: false
    # Should players be a set distance away from the chest in order for it to refill?
    # -1 to disable.
    radius: -1
  # Allow loot chests to be broken by players without the rsurv.loot permission?
  allow_chest_break: false
  common_set:
    # Item name (Bukkit names only)
    iron_sword:
      # -1 for random, or any other valid value otherwise
      durability: -1
      enchantments:
      # Yet again, -1 for random
      - "DAMAGE_ALL:-1:50-100"
      # - "RANDOM:-1"
      name: "Longsword"
      lore:
      - "A long sword made of steel."
      # one to three
      amount: "1-3"
      # Percent chance of appearance
      chance: 75
    wood:
      durability: "1-3"
      amount: "1-12"
      chance: 85
    potion:
      amount: "1-4"
      chance: 56

# Miscellaneous options
miscellaneous:
  # Since squid are wooden boxes, you can enable squid to drop random loot on kill.
  squid_loot:
    # Enable squid loot?
    enabled: true
    # Chance of squid loot in percentage
    chance: 100
    # Loot sets defined in loot chests to drop
    loot_sets:
    - "common_set"
  # Until an anvil API is implemented, repair chests will be used
  repair_chests:
    # How much damage to repair on an item in a repair chest
    repair_amount: 5
    # How often to repair items in chests in ticks
    repair_frequency: 100
  allowed_commands:
  - "login"
  - "register"
  # Prints a whole bunch of interesting dev information to console
  debug: false
  # How often to loop through all death chests (on the main thread), check if they are empty, and if they are, remove
  # them. Less than or equal to 0 is disabled.
  remove_death_chests_every: 5

# Userdata saving options
saving:
  # How often (in minutes) to save the player userdata to the disk. Userdata will be stored locally and accessed
  # locally, but it must be saved to persist. The data will be saved when the plugin is disabled, as well. This cannot
  # be set to lower than 1.
  save_interval: 5